saveExact: true
engineStrict: true
ignoreWorkspaceRootCheck: true
minimumReleaseAge: 1440
minimumReleaseAgeExcludePrune: true
trustPolicy: "no-downgrade"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
packages:
  - "."
  - "docs"
